- name: Configure sshd and sudoers
  lineinfile:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
    validate: "{{ item.validate | default(omit) }}"
    backup: no
  with_items: "{{ common_node_config_options }}"
  notify: restart ssh
  tags:
    - ssh
    - sudo
    - common

- hostname:
    name: "{{short_name}}"

- name: Update rh-amazon-rhui-client to latest
  yum:
    name: rh-amazon-rhui-client
    state: latest

- name: enable rhui repositories
  ini_file:
    dest: '/etc/yum.repos.d/redhat-rhui.repo'
    section: '{{ item }}'
    option: enabled
    value: 1
  with_items:
    - rhel-7-server-rhui-extras-rpms
    - rhel-7-server-rhui-optional-rpms

- meta: flush_handlers
  tags:
    - common
