- name: Configure sshd and sudoers
  lineinfile:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
    validate: "{{ item.validate | default(omit) }}"
    backup: no
  with_items: "{{ common_node_config_options }}"
  notify: restart ssh
  tags:
    - ssh
    - sudo
    - common

- hostname:
    name: "{{short_name}}"

- name: Update rh-amazon-rhui-client to latest
  yum:
    name: rh-amazon-rhui-client
    state: latest

- name: Copy old rhui repo file to new name
  copy: 
    remote_src: True
    src:    /etc/yum.repos.d/redhat-rhui.repo.rpmsave
    dest:   /etc/yum.repos.d/redhat-rhui-region.repo

- name: enable all RHUI repos    
  replace:
    path:     '/etc/yum.repos.d/redhat-rhui.repo'
    regexp:   '^enabled=0'
    replace:  'enabled=1'

- name: enable all old RHUI repos    
  replace:
    path:     '/etc/yum.repos.d/redhat-rhui-region.repo'
    regexp:   '^enabled=0'
    replace:  'enabled=1'

- meta: flush_handlers
  tags:
    - common
